apiVersion: v1
# type of the object
kind: Pod
metadata:
# pod name
  name: client-pod
  labels:
    component: web
spec:
  containers:
  # container name
    - name: client
      image: stephengrider/multi-worker
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 3000
